const CONFIG = {
    introTitle: 'Bé ơii',
    introDesc: `Tớ hỏi b 1 câu b phại trả lời thật lòng nháaa`,
    btnIntro: 'Ấn đây tiếp đi nàii',
    title: 'Hi b yêu tớ hemmm',
    desc: 'Hi chọn bên dưới đi nhaaa',
    btnYes: 'Cóa chớ hihii',
    btnNo: 'Không',
    question:'Ỏ b chọn cóa hãa',
    btnReply: 'Type sth then send to meee',
    reply: 'Yêu thì yêu mà không yêu thì yêu ',
    mess: 'Tớ cũng yêu bé nhiều nắm😘',
    messDesc: 'Mai mừn đi chơi nháaa',
    btnAccept: 'Okiiiii lun ',
    messLink: 'https://www.facebook.com/profile.php?id=100023062697599
